name: Update Weather Badge

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch weather data and update image
        run: node scripts/update.js

      - name: Commit and push image update
        run: |
          git config --global user.name 'lumijiez'
          git config --global user.email 'danthevip@gmail.com'
          git add --force .
          git commit -m "Updated weather image" || echo "No changes to commit"
          git push origin main --force
