name: Update Weather Badge

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch weather data and update image
        run: node scripts/update.js

      - name: Commit and push image update
        run: |
          git config --global user.name 'lumijiez'
          git config --global user.email 'danthevip@gmail.com'
          git add scripts/display/toshow.png
          git diff --cached --quiet || git commit -m 'Update weather image in toshow.png'
          git push --force
